language: rust
notifications:
    irc: "irc.mozilla.org#piston-internals"
os:
    - linux
    - osx
env:
    global:
        - secure: HLWX0NEJi2hXmxdxU5DorXI92TKBBHyYFYY7v1mrN/y0McKTI7JXq7GlUJ26VxqlxUdQLVz0NDycvlQTQ9OYMcQyZLunHiplsrTs7H+S2BZTnaTVtSdHOlNkWuml1PtJpuLEcfP9s/UHfJB+6B5MRTL9b14QFgGv8Uuxs/P9ZQc=
before_script:
    - rustc -v
    - cargo -V
script:
    - cargo build -v
    - cargo test -v
    - cargo doc -v
after_success: |
    [ $TRAVIS_BRANCH = master ] &&
    [ $TRAVIS_PULL_REQUEST = false ] &&
    cargo doc &&
    echo '<meta http-equiv=refresh content=0;url=image/index.html>' > target/doc/index.html &&
    sudo pip install ghp-import &&
    ghp-import -n target/doc &&
    git push -fq https://${GH_TOKEN}:x-oauth-basic@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
