language: rust
sudo: false
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/816755464e93a0defff0
    on_success: change
    on_failure: always
    on_start: never
os:
  - linux
rust:
  - 1.34.2
  - stable
  - beta
  - nightly
env:
  global:
    - secure: "WI/r7hbDhenb7zPXht8J0mhcx5aUgY22cCrwYmNksMmgIK9hYfPjZ68XzaQ7+Ity8b12TlHM8lGRN9bIsyAZEiRIkxkZAArY9bXAOExJaAT+yOyxhEs/QdrGB6iRhC6FTxPwgUH82j0nFL1UI7HqBnOy3g3tv23jq1AlD9N3t0k="
  matrix:
    - FEATURES=''
    - FEATURES='gif_codec'
    - FEATURES='jpeg'
    - FEATURES='png_codec'
    - FEATURES='pnm'
    - FEATURES='tga'
    - FEATURES='tiff'
    - FEATURES='webp'
    - FEATURES='hdr'
matrix:
  allow_failures:
    - name: "Clippy"
  include:
    - os: osx
      rust: 1.34.2
    - os: windows
      rust: 1.34.2
    - os: osx
      rust: stable
    - os: windows
      rust: stable
    - os: osx
      rust: nightly
    - os: windows
      rust: nightly
    - os: linux
      rust: stable
      name: "Clippy"
      script:
        - rustup component add clippy
        - cargo clippy
script:
  - if [ -z "$FEATURES" ]; then
      cargo build -v &&
      if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then cargo test -v; fi &&
      cargo doc -v;
    else
      cargo build -v --no-default-features --features "$FEATURES" &&
      if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then cargo test -v --no-default-features --features "$FEATURES"; fi &&
      cargo doc -v --no-default-features --features "$FEATURES";
    fi
  - cargo test --no-default-features
