[package]
name = "image"
version = "0.2.0-alpha"
license = "MIT"
description = "a pure rust imaging library"
authors = [
    "ccgn",
    "bvssvni <bvssvni@gmail.com>",
    "nwin",
    "TyOverby <ty@pre-alpha.com>"]
readme = "README.md"
exclude = [
    "src/png/testdata/*",
]
[lib]
name = "image"
path = "./src/lib.rs"

[dev-dependencies.glob]

git = "https://github.com/rust-lang/glob"

[dev-dependencies.num]

git = "https://github.com/rust-lang/num"
