[package]
name = "image"
version = "0.2.0-alpha.1"
license = "MIT"
description = "a pure rust imaging library"
authors = [
    "ccgn",
    "bvssvni <bvssvni@gmail.com>",
    "nwin",
    "TyOverby <ty@pre-alpha.com>"]
readme = "README.md"
documentation = "http://www.rust-ci.org/PistonDevelopers/piston/doc/image/index.html"
repository = "https://github.com/PistonDevelopers/image.git"
homepage = "https://github.com/PistonDevelopers/image"
exclude = [
    "src/png/testdata/*",
]
[lib]
name = "image"
path = "./src/lib.rs"

[dev-dependencies]
num="*"
glob="*"